CREATE DATABASE EF_MultiTable;

USE EF_MultiTable;

CREATE TABLE State (
    StateId INT PRIMARY KEY IDENTITY,
    StateName VARCHAR(100)
)

CREATE TABLE City (
    CityId INT PRIMARY KEY IDENTITY,
    CityName VARCHAR(100),
    StateId INT FOREIGN KEY REFERENCES State(StateId) ON DELETE CASCADE
)

SELECT * FROM State;
SELECT * FROM City;